"use client";
import Link from "next/link";
import { useState, type FormEvent } from "react";
import { Archive, ArrowRight, BookOpen, BrainCircuit, Check, ChevronRight, Compass, Download, Feather, Globe2, LoaderCircle, MoreHorizontal, Pencil, Play, Plus, RefreshCw, Search, ShieldCheck, Sparkles, Trash2, UserRound, X } from "lucide-react";
import { useApp } from "./app-shell";
import { WorldLibrary } from "./world-library";
import { StoryRecords } from "./story-records";
import { Dialog } from "./dialog";
import { ART, coverFor, PROFILE_LABELS, WORLDS, type Session } from "@/lib/ui-data";
import { api, shortDate } from "@/lib/api-client";
export type Section = "overview" | "campaigns" | "worlds" | "characters" | "memory" | "journal";
const headings: Record<Section, { eyebrow: string; title: string; subtitle: string }> = {
  overview: { eyebrow: "ПРИКЛЮЧЕНИЕ НАЧИНАЕТСЯ ЗДЕСЬ", title: "Хороший день для новой истории", subtitle: "Выбирайте мир, создавайте героя и оставляйте свой след." },
  campaigns: { eyebrow: "ВАШИ МИРЫ ЖДУТ ВАС", title: "Мои кампании", subtitle: "Незаконченные главы и истории, к которым хочется вернуться." },
  worlds: { eyebrow: "ВОСЕМЬ МИРОВ. ТЫСЯЧИ ПУТЕЙ.", title: "Куда заведёт воображение?", subtitle: "Найдите историю по душе — или создайте ту, которой ещё не было." },
  characters: { eyebrow: "НЕ ПРОСТО ИМЕНА В ИСТОРИИ", title: "Ваши персонажи", subtitle: "Каждый герой — новая возможность взглянуть на мир иначе." },
  memory: { eyebrow: "НИ ОДНО РЕШЕНИЕ НЕ ЗАБЫТО", title: "Память мира", subtitle: "Подтверждённые факты, знакомые лица и нити вашей истории." },
  journal: { eyebrow: "СТРАНИЦЫ ВАШИХ ПРИКЛЮЧЕНИЙ", title: "Журнал приключений", subtitle: "Вспомните, с чего всё началось, и сохраните историю для себя." },
};
export function Dashboard({ section = "overview" }: { section?: Section }) {
  const { newStory, loading, loadError, refresh } = useApp();
  const heading = headings[section];
  return <div className={`dashboard page-${section}`}><div className="page-heading"><div><div className="eyebrow">{heading.eyebrow}</div><h1>{heading.title}</h1><p>{heading.subtitle}</p></div><button className="button primary new-story-button" onClick={() => newStory()}><Plus size={17} /><span>Новая кампания</span></button></div>{loadError && <div className="notice error-notice"><ShieldCheck size={18} /><p>Не удалось загрузить сохранённые истории. {loadError}</p><button onClick={() => void refresh()} className="text-button"><RefreshCw size={14} />Повторить</button></div>}
    {section === "overview" && <><Hero /><Features /><Campaigns compact /><WorldLibrary /></>}
    {section === "worlds" && <><div className="worlds-callout"><span className="feature-icon violet"><Sparkles size={22} /></span><div><h3>Ваше воображение — единственная граница</h3><p>Любой жанр, любой герой, свои правила. Расскажите, каким будет ваш мир.</p></div><button className="button secondary" onClick={() => newStory(undefined, "free")}>Создать свой мир <ArrowRight size={15} /></button></div><WorldLibrary full /></>}
    {section === "campaigns" && <Campaigns />}{section === "characters" && <Characters />}{(section === "memory" || section === "journal") && <StoryRecords mode={section} />}
    <footer className="workspace-footer"><span><Compass size={13} />Каждый выбор становится частью истории.</span><Link href="/blueprint">Chronicle Engine <span>v2.1</span><ArrowRight size={12} /></Link></footer></div>;
}
function Hero() {
  const { newStory, showGuide } = useApp();
  const [slide, setSlide] = useState(0);
  const ids = ["ashen-crown", "neon-pact", "echo-station"];
  const world = WORLDS.find((s) => s.id === ids[slide])!;
  return <section className="hero"><img key={world.id} className="hero-image" src={coverFor(world.id)} alt={`Пейзаж мира ${world.worldName}`} fetchPriority="high" /><div className="hero-shade" /><div className="hero-content"><div className="hero-eyebrow"><Sparkles size={13} />МИРЫ, КОТОРЫЕ ПОМНЯТ ВАС</div><h2>Не просто игра.<br /><span>Твоя история.</span></h2><p>Стань кем угодно. Отправляйся куда угодно.<br />ИИ-мастер оживит мир, а каждый выбор изменит его.</p><div className="hero-actions"><button className="button primary" onClick={() => newStory(world.id)}>Начать приключение <ArrowRight size={15} /></button><button className="button hero-secondary" onClick={showGuide}><Play size={13} />Как это работает</button></div></div><div className="hero-pagination" aria-label="Обложки миров">{ids.map((id, index) => <button key={id} className={slide === index ? "active" : ""} onClick={() => setSlide(index)} aria-label={`Показать мир ${WORLDS.find((s) => s.id === id)?.title}`} aria-pressed={slide === index} />)}</div><button className="hero-world-caption" onClick={() => newStory(world.id)}><span>{world.title}</span><small><MapIcon />{world.worldName} · {ART[world.id].category}<ChevronRight size={12} /></small></button><div className="hero-corner-label">ВООБРАЖЕНИЕ БЕЗ ГРАНИЦ <span>✦</span></div></section>;
}
function MapIcon() { return <Compass size={11} />; }
function Features() {
  return <div className="features">{[{ icon: Globe2, color: "violet", title: "Любой мир. Любые правила.", text: "От магии и мечей до неона и звёзд" }, { icon: BrainCircuit, color: "teal", title: "Мир помнит ваши решения", text: "Живая память, а не случайный сюжет" }, { icon: Feather, color: "amber", title: "Свобода каждого действия", text: "Выбирайте вариант или пишите свой" }].map((feature) => <div className="feature" key={feature.title}><span className={`feature-icon ${feature.color}`}><feature.icon size={19} strokeWidth={1.5} /></span><div><h3>{feature.title}</h3><p>{feature.text}</p></div></div>)}</div>;
}
function Campaigns({ compact = false }: { compact?: boolean }) {
  const { sessions, newStory, refresh, notify, loading } = useApp();
  const [filter, setFilter] = useState("active");
  const [query, setQuery] = useState("");
  const [menu, setMenu] = useState<string | null>(null);
  const [manage, setManage] = useState<{ session: Session; action: "rename" | "delete" } | null>(null);
  const [title, setTitle] = useState("");
  const [busy, setBusy] = useState(false);
  const filtered = sessions.filter((s) => (filter === "active" ? s.status === "active" : s.status !== "active") && `${s.title} ${s.character.name}`.toLowerCase().includes(query.toLowerCase()));
  const visible = compact ? filtered.slice(0, 2) : filtered;
  const archive = async (s: Session) => {
    setMenu(null);
    try { await api(`/api/sessions/${s.id}`, { method: "PATCH", body: JSON.stringify({ status: s.status === "active" ? "archived" : "active" }) }); await refresh(); notify(s.status === "active" ? "История бережно сохранена в архиве" : "История возвращена из архива"); } catch (error) { notify(error instanceof Error ? error.message : "Не удалось обновить", true); }
  };
  const submit = async (event: FormEvent) => {
    event.preventDefault(); if (!manage) return; setBusy(true);
    try { await api(`/api/sessions/${manage.session.id}`, { method: manage.action === "delete" ? "DELETE" : "PATCH", ...(manage.action === "rename" ? { body: JSON.stringify({ title }) } : {}) }); await refresh(); notify(manage.action === "delete" ? "Кампания удалена" : "Новое название сохранено"); setManage(null); } catch (error) { notify(error instanceof Error ? error.message : "Ошибка", true); } finally { setBusy(false); }
  };
  return <section className="campaign-section"><div className="section-heading"><h2>{compact ? "Продолжить историю" : "Ваши истории"}<span className="count-badge">{sessions.filter((s) => s.status === "active").length}</span></h2>{compact ? <Link href="/campaigns" className="text-link">Все кампании <ArrowRight size={14} /></Link> : <div className="campaign-filters"><div className="segmented compact"><button className={filter === "active" ? "selected" : ""} onClick={() => setFilter("active")}>Активные</button><button className={filter !== "active" ? "selected" : ""} onClick={() => setFilter("archived")}><Archive size={12} />Архив</button></div><label className="search-field"><Search size={14} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Найти историю…" aria-label="Поиск кампаний" /></label></div>}</div><div className={`campaign-grid ${!compact ? "campaign-grid-full" : ""}`}>
      {loading && !sessions.length ? [0, 1].map((n) => <div className="campaign-skeleton" key={n}><div /><section><i /><i /><i /></section></div>) : visible.map((s) => <article className="campaign-card" key={s.id}><Link href={`/play/${s.id}`} className="campaign-card-main"><img className="campaign-thumb" src={coverFor(s.scenarioId)} alt="" /><div className="campaign-content"><div className="campaign-meta"><span className={`tiny-dot ${s.status === "active" ? "green" : ""}`} />{s.status === "active" ? "В игре" : "В архиве"}<span>·</span>Глава {s.worldState.chapter}</div><h3>{s.title}</h3><p><UserRound size={11} />{s.character.name}<span className="character-role"> · {s.character.archetype}</span></p><div className="campaign-bottom"><span className="mini-tag">{PROFILE_LABELS[s.rulesProfile]}</span><small>{s.turnCount > 1 ? `${s.turnCount - 1} действий` : "Всё только начинается"}</small></div></div></Link><button className="icon-button campaign-more" onClick={() => setMenu(menu === s.id ? null : s.id)} aria-label={`Управление кампанией ${s.title}`}><MoreHorizontal size={17} /></button><Link href={`/play/${s.id}`} className="continue-arrow" aria-label={`Продолжить ${s.title}`}><ArrowRight size={16} /></Link>{menu === s.id && <><div className="popover-dismiss" onClick={() => setMenu(null)} /><div className="campaign-menu"><button onClick={() => { setManage({ session: s, action: "rename" }); setTitle(s.title); setMenu(null); }}><Pencil size={13} />Переименовать</button><a href={`/api/sessions/${s.id}/export`} onClick={() => setMenu(null)}><Download size={13} />Скачать журнал</a><button onClick={() => void archive(s)}><Archive size={13} />{s.status === "active" ? "В архив" : "Восстановить"}</button><button className="danger-text" onClick={() => { setManage({ session: s, action: "delete" }); setMenu(null); }}><Trash2 size={13} />Удалить</button></div></>}</article>)}
      {compact && !loading && !visible.length && WORLDS.slice(0, 2).map((world) => <button key={world.id} className="campaign-card starter-campaign" onClick={() => newStory(world.id)}><img className="campaign-thumb" src={coverFor(world.id)} alt="" /><div className="campaign-content"><div className="campaign-meta">ВАША ПЕРВАЯ ИСТОРИЯ</div><h3>{world.title}</h3><p>{world.characters[0].name} · {world.characters[0].archetype}</p><span className="mini-tag">Готово к приключению</span></div><ArrowRight size={17} /></button>)}
      {(filter === "active" && (!compact || visible.length < 3)) && <button className="new-campaign-card" onClick={() => newStory()}><span><Plus size={21} strokeWidth={1.4} /></span><div><strong>Ещё одна история?</strong><p>Новый мир уже ждёт вас</p></div><ArrowRight size={15} /></button>}
    </div>{!compact && !loading && !visible.length && <div className="empty-state"><BookOpen size={30} /><h3>{filter === "active" ? "Чистая страница — отличное начало" : "В архиве пока тихо"}</h3><p>{filter === "active" ? "Создайте кампанию или попробуйте другой поисковый запрос." : "Здесь будут храниться истории, которые вы отложили."}</p></div>}
    {manage && <Dialog title={manage.action === "delete" ? "Удалить кампанию" : "Переименовать кампанию"} onClose={() => setManage(null)}><span className="dialog-emblem">{manage.action === "delete" ? <Trash2 size={24} /> : <Pencil size={24} />}</span><h2>{manage.action === "delete" ? "Закрыть историю навсегда?" : "У каждой истории есть имя"}</h2><form onSubmit={submit}>{manage.action === "rename" ? <label className="field"><span>Название кампании</span><input required maxLength={80} value={title} onChange={(e) => setTitle(e.target.value)} /></label> : <p className="dialog-intro">Кампания «{manage.session.title}», все её ходы и воспоминания будут удалены. Это действие нельзя отменить. Вместо удаления можно перенести историю в архив.</p>}<div className="dialog-actions"><button type="button" className="button secondary" onClick={() => setManage(null)}>Оставить как есть</button><button className={`button ${manage.action === "delete" ? "danger" : "primary"}`} disabled={busy}>{busy && <LoaderCircle size={14} className="spin" />}{manage.action === "delete" ? "Удалить историю" : "Сохранить"}</button></div></form></Dialog>}
  </section>;
}
function Characters() {
  const { sessions, newStory, loading } = useApp();
  const [query, setQuery] = useState("");
  const filtered = sessions.filter((s) => `${s.character.name} ${s.character.archetype} ${s.title}`.toLowerCase().includes(query.toLowerCase()));
  return <section><div className="section-heading"><h2>Герои ваших кампаний <span className="count-badge">{sessions.length}</span></h2><label className="search-field"><Search size={14} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Имя или роль…" aria-label="Поиск персонажей" /></label></div><div className="characters-grid">{filtered.map((s) => <article className="character-card" key={s.id}><div className="character-cover" style={{ backgroundImage: `url(${coverFor(s.scenarioId)})` }} /><div className="character-portrait"><UserRound size={34} strokeWidth={1.2} /></div><div className="character-card-body"><span className="pill violet">{s.character.archetype}</span><h2>{s.character.name}</h2><Link className="character-campaign" href={`/play/${s.id}`}><BookOpen size={13} />{s.title}</Link><p>{s.character.backstory}</p><div className="tag-row">{s.character.skills.map((skill) => <span className="tag" key={skill}>{skill}</span>)}</div>{s.rulesProfile === "d20" && <div className="stats-row">{Object.entries(s.character.stats).map(([key, value]) => <div key={key}><small>{key}</small><strong>{value}</strong></div>)}</div>}<Link className="button secondary full-width" href={`/play/${s.id}`}>Вернуться в историю <ArrowRight size={14} /></Link></div></article>)}</div>{!loading && !filtered.length && <div className="empty-state"><UserRound size={32} /><h3>Знакомство ещё впереди</h3><p>Создайте кампанию — и её главный герой появится здесь.</p><button className="button primary" onClick={() => newStory()}>Создать первого героя <Plus size={15} /></button></div>}</section>;
}
