"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { ArrowDown, ArrowLeft, ArrowRight, Backpack, BookOpen, BookOpenText, BrainCircuit, Check, ChevronDown, ChevronUp, Compass, Dices, Download, Feather, Flag, Globe2, Heart, LoaderCircle, MapPin, Maximize2, MessageCircle, Minimize2, Plus, RefreshCw, Send, ShieldCheck, Sparkles, Swords, UserRound, UsersRound, X } from "lucide-react";
import { useApp } from "./app-shell";
import { api, jsonBody } from "@/lib/api-client";
import { coverFor, PROFILE_LABELS, SOURCE_LABELS, type Snapshot } from "@/lib/ui-data";
import type { AppliedChanges } from "@/db/schema";
import type { TurnResponse } from "@/lib/turn";
export function PlayRoom({ sessionId }: { sessionId: string }) {
  const { settings, refresh, notify } = useApp();
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null);
  const [loadError, setLoadError] = useState("");
  const [action, setAction] = useState("");
  const [busy, setBusy] = useState(false);
  const [actionError, setActionError] = useState("");
  const [sideTab, setSideTab] = useState("hero");
  const [reading, setReading] = useState(false);
  const [compactNeeded, setCompactNeeded] = useState(false);
  const [compacting, setCompacting] = useState(false);
  const [older, setOlder] = useState<Snapshot["turns"]>([]);
  const [loadingOlder, setLoadingOlder] = useState(false);
  const [selectedChoice, setSelectedChoice] = useState(-1);
  const endRef = useRef<HTMLDivElement>(null);
  const requestRef = useRef<{ action: string; custom: boolean; id: string } | null>(null);
  const reload = useCallback(async () => {
    const result = await api<Snapshot>(`/api/sessions/${sessionId}`);
    setSnapshot(result); setLoadError(""); return result;
  }, [sessionId]);
  useEffect(() => {
    let active = true;
    api<Snapshot>(`/api/sessions/${sessionId}`).then((result) => {
      if (!active) return; setSnapshot(result);
      if (window.location.hash) setTimeout(() => document.getElementById(window.location.hash.slice(1))?.scrollIntoView({ behavior: "smooth", block: "center" }), 150);
    }).catch((e) => { if (active) setLoadError(e.message); });
    return () => { active = false; };
  }, [sessionId]);
  const act = async (text: string, custom: boolean, choice = -1) => {
    if (busy || !text.trim()) return;
    setBusy(true); setActionError(""); setSelectedChoice(choice);
    if (!requestRef.current || requestRef.current.action !== text || requestRef.current.custom !== custom) requestRef.current = { action: text, custom, id: crypto.randomUUID() };
    try {
      const result = await api<TurnResponse>(`/api/sessions/${sessionId}/act`, jsonBody({ action: text, custom, requestId: requestRef.current.id }));
      setCompactNeeded(result.needsCompaction); setAction(""); requestRef.current = null;
      await reload(); void refresh();
      setTimeout(() => document.getElementById(`turn-${result.turnNumber}`)?.scrollIntoView({ behavior: "smooth", block: "start" }), 80);
    } catch (e) { setActionError(e instanceof Error ? e.message : "Ход не завершён. Попробуйте ещё раз."); await reload().catch(() => {}); }
    finally { setBusy(false); setSelectedChoice(-1); }
  };
  const submit = (e: FormEvent) => { e.preventDefault(); void act(action, true); };
  const loadEarlier = async () => {
    if (!snapshot) return;
    const before = Math.min(...[...older, ...snapshot.turns].map((turn) => turn.turnNumber));
    setLoadingOlder(true);
    try { const result = await api<{ turns: Snapshot["turns"] }>(`/api/sessions/${sessionId}/turns?before=${before}`); setOlder((old) => [...result.turns, ...old]); } catch (e) { notify(e instanceof Error ? e.message : "Не удалось загрузить ходы", true); } finally { setLoadingOlder(false); }
  };
  const compact = async () => { setCompacting(true); try { await api(`/api/sessions/${sessionId}/compact`, jsonBody({})); await reload(); setCompactNeeded(false); notify("Новые главы сохранены в долгосрочной памяти"); } catch (e) { notify(e instanceof Error ? e.message : "Не удалось сохранить память", true); } finally { setCompacting(false); } };
  const restore = async () => { try { await api(`/api/sessions/${sessionId}`, { method: "PATCH", body: JSON.stringify({ status: "active" }) }); await reload(); void refresh(); } catch (e) { notify(e instanceof Error ? e.message : "Ошибка", true); } };
  if (loadError) return <div className="empty-state"><BookOpen size={32} /><h3>Не удалось открыть эту главу</h3><p>{loadError}</p><button className="button secondary" onClick={() => void reload().catch((e) => setLoadError(e.message))}><RefreshCw size={14} />Попробовать снова</button><Link className="text-link" href="/campaigns">Вернуться к кампаниям</Link></div>;
  if (!snapshot) return <div className="play-loading"><LoaderCircle size={30} className="spin" /><h2>Открываем вашу историю…</h2><p>Загружаем мир, персонажей и сохранённые решения.</p></div>;
  const { session, inventory, memories, locations, quests, npcs, sceneObjects } = snapshot;
  const character = session.character;
  const world = session.worldState;
  const live = Boolean(settings?.useLiveAI && settings.keysCount + settings.envKeysCount > 0);
  const turns = [...older, ...snapshot.turns].filter((turn, index, all) => all.findIndex((t) => t.id === turn.id) === index);
  const lastNarrator = [...snapshot.turns].reverse().find((turn) => turn.role === "narrator");
  const active = session.status === "active";
  return <div className={`play-room ${reading ? "reading-mode" : ""}`}><div className="play-topline"><Link href="/campaigns" className="text-link"><ArrowLeft size={14} />Мои кампании</Link><div><span className="autosave"><Check size={12} />Все изменения сохранены</span><a className="icon-button" href={`/api/sessions/${sessionId}/export`} title="Скачать историю" aria-label="Скачать историю"><Download size={16} /></a><button className="icon-button" onClick={() => setReading(!reading)} aria-label={reading ? "Выйти из режима чтения" : "Режим чтения"} title="Режим чтения">{reading ? <Minimize2 size={16} /> : <BookOpenText size={17} />}</button></div></div><div className="play-banner" style={{ backgroundImage: `linear-gradient(90deg, #12121bfa, #12121b9e 55%, #14141c25),url(${coverFor(session.scenarioId)})` }}><div className="eyebrow">ГЛАВА {world.chapter} · {session.campaignMode === "preset" ? "АВТОРСКАЯ ИСТОРИЯ" : "ВАШ СОБСТВЕННЫЙ МИР"}</div><h1>{session.title}</h1><div className="play-banner-meta"><span><MapPin size={12} />{world.currentLocation}</span><span className="pill violet">{PROFILE_LABELS[session.rulesProfile]}</span></div></div><div className="play-layout"><section className="narrative-panel"><div className="narrative-panel-heading"><span><BookOpen size={15} />Нить повествования</span><span className={live ? "live-label" : "offline-text"}><i />{live ? "ИИ-мастер Gemini" : "Автономный режим"}</span></div>{!live && <div className="play-offline-note"><Sparkles size={13} /><span>{session.campaignMode === "free" ? "Для продолжения свободной истории нужен ИИ-мастер." : "Сейчас историю ведёт упрощённый движок пресета."} <Link href="/settings">Подключить Gemini <ArrowRight size={10} /></Link></span></div>}
    {turns[0]?.turnNumber > 1 && <button className="load-earlier" onClick={() => void loadEarlier()} disabled={loadingOlder}>{loadingOlder ? <LoaderCircle size={13} className="spin" /> : <ChevronUp size={13} />}Предыдущие главы</button>}
    <div className="story-turns">{turns.map((turn) => <article className={`story-turn ${turn.role === "player" ? "player-turn" : "narrator-turn"}`} key={turn.id} id={`turn-${turn.turnNumber}${turn.role === "player" ? "-player" : ""}`}><div className="turn-label"><span className="turn-avatar">{turn.role === "player" ? <UserRound size={14} /> : <Feather size={14} />}</span><strong>{turn.role === "player" ? character.name : "Рассказчик"}</strong><span>Ход {turn.turnNumber}</span>{turn.role !== "player" && <span className="turn-model">{turn.modelUsed?.startsWith("gemini") ? "AI" : turn.modelUsed?.includes("intro") ? "ПРОЛОГ" : "ОФЛАЙН"}</span>}</div><div className="turn-prose">{turn.content}</div>{turn.dice && <div className={`dice-result ${turn.dice.success ? "dice-success" : "dice-failure"}`}><span className="dice-number"><Dices size={23} /><strong>{turn.dice.total}</strong></span><div><strong>{turn.dice.skill || turn.dice.label}</strong><small>{turn.dice.kind === "2d6" ? "Проверка риска · 2d6" : `Серверный d20 · сложность ${turn.dice.dc}`}</small></div><span>{turn.dice.band === "cost" ? "Успех с ценой" : turn.dice.success ? "Успех" : "Неудача"}</span></div>}{turn.stateChanges && <AppliedChips applied={turn.stateChanges} />}</article>)}</div>
    {busy && <div className="thinking-state" aria-live="polite"><Sparkles size={19} /><span>{live ? "Мастер вплетает ваше решение в историю" : "Мир отвечает на ваш выбор"}<small>Состояние изменится только после проверки сервера.</small></span><i /><i /><i /></div>}
    <div ref={endRef} className="action-area">{!active ? <div className="empty-state"><BookOpen size={23} /><h3>Эта история ждёт в архиве</h3><p>Прочитайте предыдущие главы или вернитесь к приключению.</p><button className="button primary" onClick={() => void restore()}>Продолжить историю <ArrowRight size={14} /></button></div> : <><div className="action-heading"><Sparkles size={14} /><h3>Что вы сделаете дальше?</h3></div>{lastNarrator?.choices?.length ? <div className="action-choices">{lastNarrator.choices.map((choice, i) => <button key={`${i}-${choice}`} onClick={() => void act(choice, false, i)} disabled={busy}><span>{selectedChoice === i ? <LoaderCircle size={13} className="spin" /> : String(i + 1).padStart(2, "0")}</span><p>{choice}</p><ArrowRight size={14} /></button>)}</div> : <p className="free-start-note">Первое слово — за вами. Опишите действие, с которого всё начнётся.</p>}<div className="or-divider"><span />ИЛИ ВЫБЕРИТЕ СВОЙ ПУТЬ<span /></div><form onSubmit={submit} className="action-form"><textarea id="action-input" aria-label="Ваше действие" placeholder="Я хочу… Опишите своё действие" value={action} onChange={(e) => setAction(e.target.value)} maxLength={2000} rows={2} disabled={busy} onKeyDown={(e) => { if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) { e.preventDefault(); void act(action, true); } }} /><div><span>{action.length ? `${action.length} / 2000` : "Любое действие. Ваш выбор имеет значение."}</span><button className="button primary" disabled={busy || !action.trim()}>{busy ? <LoaderCircle size={14} className="spin" /> : <Send size={14} />}Сделать ход</button></div></form><div className="action-footnote"><ShieldCheck size={11} />Модель предлагает — сервер проверяет.<span>⌘ / Ctrl + Enter</span></div></>}{actionError && <div className="notice error-notice" role="alert"><ShieldCheck size={16} /><p>{actionError}{!live && session.campaignMode === "free" && <> <Link href="/settings">Открыть настройки</Link></>}</p></div>}{compactNeeded && <div className="notice"><BrainCircuit size={17} /><p>Приключение стало длиннее. Сохраните последние главы в долгосрочной памяти.</p><button className="text-button" disabled={compacting} onClick={() => void compact()}>{compacting ? "Сохраняем…" : "Обобщить"}</button></div>}</div></section>
    {!reading && <aside className="story-sidebar"><div className="story-side-tabs" role="tablist" aria-label="Состояние мира">{[{ id: "hero", icon: UserRound, title: "Герой" }, { id: "inventory", icon: Backpack, title: "Вещи" }, { id: "world", icon: Globe2, title: "Мир" }, { id: "memory", icon: BrainCircuit, title: "Память" }].map((tab) => <button role="tab" aria-selected={sideTab === tab.id} key={tab.id} className={sideTab === tab.id ? "active" : ""} onClick={() => setSideTab(tab.id)}><tab.icon size={17} /><span>{tab.title}</span></button>)}</div><div className="story-side-content">
      {sideTab === "hero" && <><div className="hero-identity"><span><UserRound size={29} strokeWidth={1.3} /></span><div><h2>{character.name}</h2><p>{character.archetype}</p></div></div><p className="hero-backstory">{character.backstory}</p>{session.rulesProfile !== "narrative" && <><div className="resource-label"><span><Heart size={13} />{session.rulesProfile === "d20" ? "Здоровье" : "Состояние"}</span><strong>{character.hp} <small>/ {character.maxHp}</small></strong></div><div className="progress-track health"><i style={{ width: `${character.maxHp ? character.hp / character.maxHp * 100 : 0}%` }} /></div><div className="resource-grid">{session.rulesProfile === "d20" && <div><small>УРОВЕНЬ</small><strong>{character.level}</strong></div>}<div><small>СРЕДСТВА</small><strong>{character.gold}</strong></div>{session.rulesProfile === "d20" && <div><small>ОПЫТ</small><strong>{character.xp}</strong></div>}</div></>}{session.rulesProfile === "d20" && <div className="stats-row">{Object.entries(character.stats).map(([key, value]) => <div key={key}><small>{key}</small><strong>{value}</strong></div>)}</div>}<div className="side-section-title">НАВЫКИ И ЧЕРТЫ</div><div className="tag-row">{[...character.skills, ...character.traits].map((skill) => <span key={skill} className="tag">{skill}</span>)}</div>{!!character.conditions?.length && <><div className="side-section-title">СОСТОЯНИЯ</div><div className="tag-row">{character.conditions.map((condition) => <span key={condition} className="pill amber">{condition}</span>)}</div></>}<div className="side-section-title"><Flag size={12} />ЦЕЛИ ИСТОРИИ</div>{quests.map((quest) => <div className="quest-item" key={quest.id}><div><span className={`tiny-dot ${quest.status === "completed" ? "green" : ""}`} /><strong>{quest.title}</strong></div><p>{quest.status === "completed" ? "Завершено" : quest.status === "failed" ? "Провалено" : quest.isMain ? "Главная цель" : "Побочная цель"}<span>{quest.progress}%</span></p><div className="progress-track"><i style={{ width: `${quest.progress}%` }} /></div></div>)}</>}
      {sideTab === "inventory" && <><div className="side-section-title no-top-margin">С СОБОЙ · {inventory.length}</div><p className="side-hint">Вещи — часть мира, а не просто список. Укажите предмет в своём действии.</p><div className="inventory-list">{inventory.map((item) => <div className="inventory-item" key={item.id}><span className="item-icon">{item.icon}</span><div><h3>{item.name}{item.quantity > 1 && <span> ×{item.quantity}</span>}</h3><p>{item.description}</p>{item.equipped && <small><Check size={10} />Экипировано</small>}<button onClick={() => { setAction(`Использовать «${item.name}»: `); document.getElementById("action-input")?.focus(); }} className="text-link" disabled={busy || !active}>Добавить в действие <Plus size={10} /></button></div></div>)}</div>{!inventory.length && <p className="empty-inline">С собой пока ничего нет.</p>}</>}
      {sideTab === "world" && <><div className="world-location-card"><MapPin size={22} /><small>ВЫ НАХОДИТЕСЬ ЗДЕСЬ</small><h3>{world.currentLocation}</h3><p>{world.worldName}</p></div><div className="side-section-title">ИЗВЕСТНЫЕ ЛОКАЦИИ</div><div className="location-list">{locations.filter((location) => location.discovered).map((location) => <div key={location.id} className={location.current ? "current" : ""}><Compass size={15} /><span><strong>{location.name}</strong><small>{location.description}</small></span>{location.current && <Check size={13} />}</div>)}</div>{!!sceneObjects.length && <><div className="side-section-title">ОКРУЖЕНИЕ</div>{sceneObjects.filter((object) => object.locationName === world.currentLocation).map((object) => <div className="scene-object" key={object.id}><strong>{object.name}</strong><span>{object.state}</span><p>{object.description}</p></div>)}</>}<div className="side-section-title">ЗНАКОМЫЕ ЛИЦА</div>{npcs.length ? npcs.map((npc) => <div className="npc-row" key={npc.id}><UserRound size={18} /><div><strong>{npc.name}</strong><small>{npc.role} · {npc.status === "dead" ? "Погиб" : npc.relation > 0 ? "Расположен к вам" : npc.relation < 0 ? "Не доверяет" : "Нейтрален"}</small></div><span>{npc.relation > 0 ? "+" : ""}{npc.relation}</span></div>) : <p className="side-hint">Новые знакомства ещё впереди.</p>}</>}
      {sideTab === "memory" && <><div className="side-section-title no-top-margin"><BrainCircuit size={14} />МИР ПОМНИТ</div><p className="side-hint">Факты с подтверждённым источником. Они помогают истории оставаться последовательной.</p>{memories.slice(0, 7).map((memory) => <div className="memory-side-item" key={memory.id}><span>{SOURCE_LABELS[memory.source]}</span><h3>{memory.title}</h3><p>{memory.content}</p></div>)}<Link href={`/memory?session=${sessionId}`} className="button secondary full-width">Вся память мира <ArrowRight size={13} /></Link></>}
      </div><div className="side-footer"><ShieldCheck size={12} />Состояние подтверждено сервером</div></aside>}
    </div><footer className="workspace-footer"><span><Compass size={13} />Это ваша история. Делайте её своей.</span><Link href="/blueprint">Chronicle Engine v2.1 <ArrowRight size={12} /></Link></footer></div>;
}
function AppliedChips({ applied }: { applied: AppliedChanges }) {
  const changes = [applied.location && `Локация: ${applied.location.to}`, applied.hp && `Здоровье ${applied.hp > 0 ? "+" : ""}${applied.hp}`, applied.xp && `Опыт +${applied.xp}`, applied.gold && `Средства ${applied.gold > 0 ? "+" : ""}${applied.gold}`, ...applied.inventory.filter((item) => item.ok).map((item) => `${item.op === "add" ? "+" : item.op === "consume" || item.op === "remove" ? "−" : ""} ${item.name} ×${item.quantity}`), ...applied.quests.map((quest) => `${quest.title}: ${quest.progress}%`), ...applied.conditions.added.map((condition) => `Состояние: ${condition}`)].filter(Boolean);
  return <>{!!changes.length && <div className="applied-chips">{changes.map((change, i) => <span key={i}><Check size={10} />{change}</span>)}</div>}{!!applied.rejected.length && <details className="rejected-changes"><summary>Сервер не применил {applied.rejected.length} изменений</summary>{applied.rejected.map((reason, i) => <p key={i}>{reason}</p>)}</details>}</>;
}
