import type { Scenario } from "./narrative-evaluation-fixtures";

// Authored and labelled before any held-out provider call. Labels are not model-generated.
export type HeldoutScenario = Scenario & { rationale: string };
function make(id: string, expected: Scenario["expected"], narration: string, rationale: string, state: Record<string, unknown> = {}, flags: Partial<Scenario> = {}): HeldoutScenario {
  return { id, expected, rationale, narration, shouldGuard: true, action: "Проверяю результат.", declaration: { mode: "event", referencesPast: false }, hasDice: false, hasStateChanges: false, rejected: [], ...flags,
    state: { currentTurn: 20, scope: "accepted_changes — только ход 20; before_state полностью описывает переданные коллекции и поля. Отсутствующие поля неизвестны. historical_evidence — единственные доступные исторические источники.", before_state: { location: "порт", gold: 12, inventory: [], npcs: [] }, accepted_changes: [], rejected_changes: [], historical_evidence: [], draft_choices: [], ...state, draft: narration } };
}
const pact = { turn: 4, role: "narrator", authority: "confirmed_event", text: "Сава обязался дать герою лодку после доставки соли до заката. Герой согласился. Договор не касается меча." };
const amendment = { turn: 11, role: "narrator", authority: "confirmed_event", text: "Сава и герой изменили только срок: соль надо доставить до рассвета. Остальные условия сохранены." };
const history = { historical_evidence: [pact, amendment] };
const trade = { before_state: { location: "порт", gold: 12, inventory: [] }, accepted_changes: [{ type: "inventory.add", item: "компас" }, { type: "gold", delta: -4, after: 8 }, { type: "move", from: "порт", to: "маяк" }] };
export const heldoutScenarios: HeldoutScenario[] = [
  make("h01_trade_move", "consistent", "Заплатив четыре монеты, ты получаешь компас и переходишь к маяку. Осталось восемь монет.", "Все три принятые операции и остаток совпадают.", trade, { hasStateChanges: true }),
  make("h02_trade_partial", "consistent", "Теперь ты у маяка с компасом.", "Можно не перечислять каждую принятую операцию.", trade, { hasStateChanges: true }),
  make("h03_denied_negation", "consistent", "Ты не получил лодку и не покинул порт.", "Оба отклонённых события явно отрицаются.", { rejected_changes: ["inventory.add: лодка", "move: море"], accepted_outcome: "Лодка не получена; герой остаётся в порту" }, { rejected: ["inventory.add", "move"] }),
  make("h04_conditional_choice", "consistent", "Ты держишь компас.", "Компас уже есть; условное предложение не утверждает получение лодки.", { before_state: { inventory: ["компас"], location: "порт" }, draft_choices: ["Если найдётся лодка, попробовать договориться о переправе"] }),
  make("h05_amended_deadline", "consistent", "По договору Сава даст лодку после доставки соли до рассвета.", "Поправка меняет срок, сохраняет предмет и условие.", history),
  make("h06_historical_old_version", "consistent", "Сначала сроком был закат, но позже стороны перенесли его на рассвет.", "Явно описаны старое и новое условия, а не устаревшее как действующее.", history),
  make("h07_object_negation", "consistent", "Сава не обещал меч: речь шла о лодке.", "Источник явно отрицает меч и подтверждает лодку.", history),
  make("h08_existing_owned_choice", "consistent", "Фонарь по-прежнему у тебя.", "Предмет в исходном инвентаре, новая операция не нужна.", { before_state: { inventory: ["фонарь"], location: "порт" }, draft_choices: ["Осветить путь своим фонарём"] }),
  make("h09_failed_attempt", "consistent", "Ты пытаешься поднять решётку, но она остаётся закрытой.", "Попытка согласована с провалом и не утверждает успех.", { before_state: { gate: "closed" }, dice: { total: 3, outcome: "failure", goal: "открыть решётку" }, accepted_outcome: "Решётка осталась закрытой", rejected_changes: ["gate.open"] }, { hasDice: true, rejected: ["gate.open"] }),
  make("h10_cost_health", "consistent", "Ты вырываешься из ловушки, поранив руку. Здоровье снизилось с десяти до восьми.", "Приняты успех с ценой и точное изменение здоровья.", { before_state: { hp: 10, trapped: true }, accepted_changes: [{ type: "hp", delta: -2, after: 8 }, { type: "flag", trapped: false }], dice: { outcome: "cost", goal: "выбраться из ловушки" }, accepted_outcome: "Герой выбрался, потеряв два здоровья" }, { hasDice: true, hasStateChanges: true }),
  make("h11_npc_location", "consistent", "Ирина остаётся в порту, а ты прибываешь к маяку.", "Движение героя не меняет местонахождение NPC.", { before_state: { location: "порт", npcs: [{ name: "Ирина", status: "alive", location: "порт" }] }, accepted_changes: [{ type: "move", from: "порт", to: "маяк" }] }, { hasStateChanges: true }),
  make("h12_unfulfilled_promise", "consistent", "Сава обещал лодку, но пока её не передал.", "Историческое обязательство не равно исполнению.", { historical_evidence: [pact, { turn: 19, role: "narrator", authority: "confirmed_event", text: "Соль ещё не доставлена; лодка остаётся у Савы, договор не исполнен." }] }),
  make("h13_one_wrong_clause", "contradicts", "Ты получаешь компас и прибываешь к маяку; осталось десять монет.", "Две истинные части не оправдывают неверный остаток.", trade, { hasStateChanges: true }),
  make("h14_swapped_party", "contradicts", "По договору Ирина обязана дать тебе лодку за соль.", "Подмена стороны: обещал Сава.", history),
  make("h15_swapped_object", "contradicts", "Сава обещал тебе меч после доставки соли.", "Предмет подменён и явно исключён источником.", history),
  make("h16_waived_condition", "contradicts", "По действующему договору Сава отдаст лодку без доставки соли.", "Поправка срока не отменяет встречное обязательство.", history),
  make("h17_old_deadline_current", "contradicts", "Действующий срок доставки соли — закат, как и прежде.", "Поздняя поправка заменяет срок рассветом.", history),
  make("h18_promise_completed", "contradicts", "Договор с Савой уже исполнен: лодка передана тебе.", "Явное подтверждение неисполнения противоречит черновику.", { historical_evidence: [pact, { turn: 19, role: "narrator", authority: "confirmed_event", text: "Договор ещё не исполнен: лодку герой не получил." }] }),
  make("h19_negation_reversed", "contradicts", "Нельзя сказать, что ты не получил лодку: она теперь твоя.", "Двойное отрицание утверждает отклонённое приобретение.", { rejected_changes: ["inventory.add: лодка"], accepted_outcome: "Лодка не получена" }, { rejected: ["inventory.add"] }),
  make("h20_removed_item_choice", "contradicts", "Ты стоишь у причала.", "Предложение требует предмет, который удалён на этом ходу.", { before_state: { inventory: ["фонарь"] }, accepted_changes: [{ type: "inventory.remove", item: "фонарь" }], draft_choices: ["Зажечь фонарь из своего инвентаря"] }, { hasStateChanges: true }),
  make("h21_cost_omitted_denied", "contradicts", "Ты выбрался из ловушки без единой царапины; здоровье осталось десять.", "Не просто пропуск цены, а явное отрицание принятого ущерба.", { before_state: { hp: 10 }, accepted_changes: [{ type: "hp", delta: -2, after: 8 }], dice: { outcome: "cost", goal: "выбраться" }, accepted_outcome: "Выбрался, потеряв два здоровья" }, { hasDice: true, hasStateChanges: true }),
  make("h22_resurrection", "contradicts", "Егор вовсе не мёртв: он жив и говорит с тобой.", "Подтверждённая смерть и отсутствие воскрешения.", { before_state: { npcs: [{ name: "Егор", status: "dead" }] } }),
  make("h23_unknown_inventory", "insufficient", "Твой рубин лежит у тебя в кармане.", "Инвентарь не передан; отсутствие поля не означает ни владения, ни отсутствия.", { before_state: { location: "порт" } }),
  make("h24_summary_specific_terms", "insufficient", "Согласно договору, Сава должен передать тебе две лодки завтра.", "Сводка не содержит предмета, количества и срока.", { historical_evidence: [{ turn: 4, role: "derived_summary", text: "Сава и герой о чём-то договорились." }] }),
  make("h25_ambiguous_same_turn", "insufficient", "Награда по договору — лодка.", "Два равноправных источника без порядка или признака замены противоречат друг другу.", { historical_evidence: [{ turn: 4, role: "narrator", authority: "confirmed_event", text: "Награда по договору с Савой — лодка." }, { turn: 4, role: "narrator", authority: "confirmed_event", text: "Награда по договору с Савой — телега." }] }),
  make("h26_request_as_acceptance", "insufficient", "Сава согласился подарить тебе маяк.", "Просьба игрока не устанавливает согласие NPC.", { historical_evidence: [{ turn: 18, role: "player", text: "Прошу Саву подарить мне маяк." }] }),
  make("h27_extra_event", "insufficient", "Ты получаешь компас, платишь четыре монеты и прибываешь к маяку. Там тебе дарят лодку.", "Три подтверждённых события не доказывают четвёртое.", trade, { hasStateChanges: true }),
  make("h28_unproven_date", "insufficient", "Договор с Савой был заключён ровно три дня назад.", "Номера ходов не устанавливают календарные интервалы.", history),
];
